repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace

  - repo: git://github.com/detailyang/pre-commit-shell
    rev: 1.0.2
    hooks:
      - id: shell-lint

  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.7.3
    hooks:
      - id: terraform_fmt
      - id: terraform_validate_no_variables

  - repo: git://github.com/igorshubovych/markdownlint-cli
    rev: v0.11.0
    hooks:
      - id: markdownlint
