version: 2
jobs:
  validate:
    docker:
      - image: trussworks/circleci-docker-primary:8122ec14fdda6e5f18457385e4c70351c2d54523
    steps:
      - checkout
      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run:
          name: Run pre-commit tests
          command: pre-commit run --all-files --show-diff-on-failure
      - save_cache:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit

workflows:
  version: 2
  validate:
    jobs:
      - validate
