name: terraform-docs-gh-actions
on:
  push:
    branches:
      - automate-docs
jobs:
  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    - name: checkout project
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Render terraform docs inside the USAGE.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v0.6.1
      with:
        working-dir: .
        output-file: USAGE.md
        output-method: inject
        git-push: "true"