name: terraform-docs-gh-actions
on:
  push:
    branches:
      - automate-docs
jobs:
  docs:
    steps:
    - uses: terraform-docs/gh-actions@v0.6.1
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the USAGE.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v0.6.1
      with:
        working-dir: .
        output-file: USAGE.md
        output-method: inject
        git-push: "true"